import { useEffect } from 'react';
import Head from 'next/head';
import axios from 'axios';

export default function Home() {
	// useEffect(() => {
	// 	axios
	// 		.post('/api/createCompany', {
	// 			companyName: 'farmtopia',
	// 			password: 'test1234',
	// 			passwordConfirm: 'test1234',
	// 		})
	// 		.then((res) => {
	// 			console.log(res.message);
	// 		})
	// 		.catch((err) => {
	// 			console.log(err.message);
	// 		});
	// }, []);

	// axios
	// 	.post('/api/createCompany', {
	// 		companyName: 'farmtopia',
	// 		password: 'test1234',
	// 		passwordConfirm: 'test1234',
	// 	})
	// 	.then((res) => {
	// 		console.log(res.message);
	// 	})
	// 	.catch((err) => {
	// 		console.log(err.message);
	// 	});

	// useEffect(() => {
	// 	axios
	// 		.get('/api/logs/getEventLog')
	// 		.then((res) => {
	// 			console.log(res.message);
	// 		})
	// 		.catch((err) => {
	// 			console.log(err.message);
	// 		});
	// }, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
}
